build_failure_conditions:
    - 'issues.new.exists'
    - 'elements.rating(<= C).new.exists'
    - 'patches.new.exists'

filter:
    excluded_paths:
        - 'app/*'
        - 'tests/*'
        - 'bin/*'
        - 'features/*'

build:
    environment:
        php:
            version: 7.0.7
        mysql: false
        postgresql: false
        redis: false
    dependencies:
        override:
            - 'echo "We are not building dependencies."'
    tests:
        override:
            - 'echo "We are not running tests here, go to travis."'

checks:
    php:
        remove_extra_empty_lines: true
        uppercase_constants: true
        use_self_instead_of_fqcn: true
        simplify_boolean_return: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        properties_in_camelcaps: true
        prefer_while_loop_over_for_loop: true
        phpunit_assertions: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        overriding_parameter: true
        no_short_variable_names:
            minimum: '3'
        no_short_method_names:
            minimum: '3'
        optional_parameters_at_the_end: true
        no_long_variable_names:
            maximum: '20'
        no_goto: true
        more_specific_types_in_doc_comments: true
        line_length:
            max_length: '180'
        function_in_camel_caps: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: false
        fix_line_ending: true
        encourage_single_quotes: true
        encourage_postdec_operator: true
        classes_in_camel_caps: true
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
        avoid_todo_comments: true
        avoid_perl_style_comments: true
        avoid_multiple_statements_on_same_line: true
        avoid_fixme_comments: true
        avoid_unnecessary_concatenation: false
        excluded_dependencies:

coding_style:
    php: {  }